{% set name = "memo" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/memo-{{ version }}.tar.gz
  sha256: 73555eebaf82d53618a0faf015d475d352b3a2719adbce4eb19bf599f03e9e41

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - joblib >=1.0.1
    - orjson >=3.4.5
    - python >={{ python_min }}
    - rich >=9.2.0

test:
  imports:
    - memo
    - tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/koaning/memo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: memo contains decorators that can help you route the input/output of functions to files/dataframes and other sources.
  doc_url: https://koaning.github.io/memo/
  dev_url: https://github.com/koaning/memo

extra:
  recipe-maintainers:
    - koaning
    - royalts
